[install]
# Explicitly set the linker to isolated
linker = "isolated"

[test]
preload = "./happydom.ts"
coverage = true
root = "./test/unit"
coverageThreshold = { line = 1.0, function = 1.0, statement = 1.0 }
coveragePathIgnorePatterns = [
    "src/models/openapi-ts/**",
    "happydom.ts",
    "test/**",
]
